[2025-09-03T15:17:56.184+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-03T15:17:56.196+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cs_ingestion_monthly.fetch_for_interval manual__2025-09-03T15:17:54.480619+00:00 [queued]>
[2025-09-03T15:17:56.199+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cs_ingestion_monthly.fetch_for_interval manual__2025-09-03T15:17:54.480619+00:00 [queued]>
[2025-09-03T15:17:56.199+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-03T15:17:56.203+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_for_interval> on 2025-09-03 15:17:54.480619+00:00
[2025-09-03T15:17:56.206+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'cs_ingestion_monthly', 'fetch_for_interval', 'manual__2025-09-03T15:17:54.480619+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_cs.py', '--cfg-path', '/tmp/tmpkr6zpz2g']
[2025-09-03T15:17:56.207+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=517) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-03T15:17:56.207+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask fetch_for_interval
[2025-09-03T15:17:56.207+0000] {standard_task_runner.py:63} INFO - Started process 519 to run task
[2025-09-03T15:17:56.226+0000] {task_command.py:426} INFO - Running <TaskInstance: cs_ingestion_monthly.fetch_for_interval manual__2025-09-03T15:17:54.480619+00:00 [running]> on host 18f4cd224f83
[2025-09-03T15:17:56.346+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cs_ingestion_monthly' AIRFLOW_CTX_TASK_ID='fetch_for_interval' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T15:17:54.480619+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-03T15:17:54.480619+00:00'
[2025-09-03T15:17:56.347+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-03T15:17:56.347+0000] {dag_cs.py:69} INFO - Window: 2025-08-01 00:00:00 -> 2025-08-31 23:59:00 (inclusive end)
[2025-09-03T15:17:56.347+0000] {dag_cs.py:75} ERROR - Failed to import ingestion module. Check PYTHONPATH mount and volume.
Traceback (most recent call last):
  File "/opt/airflow/dags/dag_cs.py", line 73, in fetch_for_interval
    from ingestion.ingestion_cs import build_cs_query, fetch_window
ModuleNotFoundError: No module named 'ingestion'
[2025-09-03T15:17:56.348+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-03T15:17:56.348+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_cs.py", line 73, in fetch_for_interval
    from ingestion.ingestion_cs import build_cs_query, fetch_window
ModuleNotFoundError: No module named 'ingestion'
[2025-09-03T15:17:56.351+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=cs_ingestion_monthly, task_id=fetch_for_interval, run_id=manual__2025-09-03T15:17:54.480619+00:00, execution_date=20250903T151754, start_date=20250903T151756, end_date=20250903T151756
[2025-09-03T15:17:56.354+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task fetch_for_interval (No module named 'ingestion'; 519)
[2025-09-03T15:17:56.393+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-03T15:17:56.404+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-03T15:17:56.405+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
