[2025-09-03T15:44:46.277+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: cs_ingestion_manual_or_scheduled.run_ingestion_for_window scheduled__2025-08-01T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
