[2025-09-03T16:03:08.985+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-03T16:03:08.998+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cs_ingestion_monthly.fetch_for_interval manual__2025-09-03T15:58:07.446678+00:00 [queued]>
[2025-09-03T16:03:09.001+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cs_ingestion_monthly.fetch_for_interval manual__2025-09-03T15:58:07.446678+00:00 [queued]>
[2025-09-03T16:03:09.001+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-03T16:03:09.006+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_for_interval> on 2025-09-03 15:58:07.446678+00:00
[2025-09-03T16:03:09.009+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'cs_ingestion_monthly', 'fetch_for_interval', 'manual__2025-09-03T15:58:07.446678+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_cs.py', '--cfg-path', '/tmp/tmpkszt3890']
[2025-09-03T16:03:09.010+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=377) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-03T16:03:09.010+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask fetch_for_interval
[2025-09-03T16:03:09.011+0000] {standard_task_runner.py:63} INFO - Started process 378 to run task
[2025-09-03T16:03:09.031+0000] {task_command.py:426} INFO - Running <TaskInstance: cs_ingestion_monthly.fetch_for_interval manual__2025-09-03T15:58:07.446678+00:00 [running]> on host 5738e3608064
[2025-09-03T16:03:09.063+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cs_ingestion_monthly' AIRFLOW_CTX_TASK_ID='fetch_for_interval' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T15:58:07.446678+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-03T15:58:07.446678+00:00'
[2025-09-03T16:03:09.063+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-03T16:03:09.063+0000] {dag_cs.py:47} INFO - Starting ingestion task
[2025-09-03T16:03:09.063+0000] {dag_cs.py:72} INFO - Processing window: 2025-08-01 00:00:00 -> 2025-09-01 00:00:00
[2025-09-03T16:03:09.064+0000] {dag_cs.py:79} WARNING - Package function import failed (No module named 'ingestion'); trying package module
[2025-09-03T16:03:09.064+0000] {dag_cs.py:86} WARNING - Package module import failed (No module named 'ingestion'); trying top-level module
[2025-09-03T16:03:09.065+0000] {dag_cs.py:155} ERROR - Task failed with error: No module named 'feedparser'
[2025-09-03T16:03:09.065+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-03T16:03:09.065+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/dag_cs.py", line 76, in run_ingestion_for_window
    from ingestion.ingestion_cs import build_cs_query, fetch_window
ModuleNotFoundError: No module named 'ingestion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/dag_cs.py", line 81, in run_ingestion_for_window
    from ingestion import ingestion_cs as _mod
ModuleNotFoundError: No module named 'ingestion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_cs.py", line 88, in run_ingestion_for_window
    _mod2 = importlib.import_module("ingestion_cs")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/ingestion/ingestion_cs.py", line 2, in <module>
    import feedparser
ModuleNotFoundError: No module named 'feedparser'
[2025-09-03T16:03:09.070+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=cs_ingestion_monthly, task_id=fetch_for_interval, run_id=manual__2025-09-03T15:58:07.446678+00:00, execution_date=20250903T155807, start_date=20250903T160308, end_date=20250903T160309
[2025-09-03T16:03:09.074+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task fetch_for_interval (No module named 'feedparser'; 378)
[2025-09-03T16:03:09.110+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-03T16:03:09.121+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-03T16:03:09.123+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
